# Generated by Django 6.0.4 on 2026-04-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_employee_remove_workspace_user_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprerecord',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='employeeprerecord',
            name='resignation_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_workspace',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_workspaces',
            field=models.ManyToManyField(blank=True, related_name='employees', to='attendance.workspace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_hr',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
