# Generated by Django 6.0.4 on 2026-04-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_employeeprerecord_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
