# Generated by Django 6.0.4 on 2026-04-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tax_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
