# Generated by Django 6.0.4 on 2026-04-26 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_user_bank_account_number_user_tax_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_penalty_flat_rate', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('overtime_rate_multiplier', models.FloatField(default=1.5)),
            ],
            options={
                'verbose_name': 'Payroll Configuration',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.FloatField(default=0.0)),
                ('overtime_hours', models.FloatField(default=0.0)),
                ('late_instances_count', models.IntegerField(default=0)),
                ('hourly_rate_snapshot', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lateness_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='UNPAID', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.payrollperiod')),
            ],
        ),
    ]
