# Generated by Django 6.0.4 on 2026-04-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrollconfiguration_payrollperiod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='hourly_rate_snapshot',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='lateness_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
