# Generated by Django 6.0.4 on 2026-04-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_salary_paid_at_salary_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HR', 'HR')], default='EMPLOYEE', max_length=20),
        ),
    ]
