# Generated by Django 6.0.4 on 2026-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_code',
            field=models.CharField(blank=True, help_text='e.g., 057 for Zenith, 999992 for OPay', max_length=10, null=True),
        ),
    ]
