# Generated by Django 6.0.4 on 2026-05-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_user_bank_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tax_id',
        ),
    ]
