# Generated by Django 6.0.4 on 2026-05-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_remove_user_tax_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollconfiguration',
            name='late_penalty_flat_rate',
        ),
        migrations.AddField(
            model_name='payrollconfiguration',
            name='default_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=2000.0, help_text='Default hourly rate for all employees.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payrollconfiguration',
            name='late_penalty_per_minute',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Amount deducted per minute of lateness.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollconfiguration',
            name='overtime_rate_multiplier',
            field=models.FloatField(default=3.0, help_text='Multipier for overtime hours.'),
        ),
    ]
