"""
Django settings for automated_payroll_system project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import environ
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cxr!ks)vl=5yb7jathp(_ebjlgh#(4-vyf=l5ke=jdxkcx_4)g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "whitenoise.runserver_nostatic",
    'django.contrib.staticfiles',
    'attendance',
    'payroll',
    'authentication',
    'django.contrib.gis',
    'rest_framework',
    # 'rest_framework_gis',
    'corsheaders',
    'drf_spectacular',
    'leaflet',
    'rest_framework_simplejwt.token_blacklist',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Must be at the top
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'automated_payroll_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'automated_payroll_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases




env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

DATABASES = {
    # This reads the 'DATABASE_URL' variable regardless of where it's running
    'default': env.db(), 
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'
import os

# Scroll down to where STATIC_URL is defined
STATIC_URL = 'static/'

# Add this line to tell Django where your static folders are
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


STORAGES = {
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}



# settings.py
AUTH_USER_MODEL = 'payroll.User'  # Format: 'app_name.ModelName'



# # Only for Windows users
# if os.name == 'nt':
#     # This path must match exactly where you installed PostgreSQL
#     POSTGIS_PATH = r'C:\Program Files\PostgreSQL\18\bin'
#     os.environ['PATH'] = POSTGIS_PATH + os.pathsep + os.environ['PATH']




# Professional fix for your specific Windows setup
if os.name == 'nt':
    # This is the path you found
    OSGEO4W_ROOT = r'C:\Users\Perfect\AppData\Local\Programs\OSGeo4W'
    
    # Adding the bin folder to the system path so Django can see it
    os.environ['PATH'] = os.path.join(OSGEO4W_ROOT, 'bin') + os.pathsep + os.environ['PATH']
    
    # Pointing to the specific files Django needs
    GDAL_LIBRARY_PATH = os.path.join(OSGEO4W_ROOT, 'bin', 'gdal312.dll')
    GEOS_LIBRARY_PATH = os.path.join(OSGEO4W_ROOT, 'bin', 'geos_c.dll')

# settings.py

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (6.5244, 3.3792),
    'DEFAULT_ZOOM': 12,
    'TILES': [
        ('Main Map', 'https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', 
         '© OpenStreetMap contributors, Tiles style by Humanitarian OpenStreetMap Team'),
    ],
    'ATTRIBUTION_PREFIX': 'Powered by HR Systems',
    # Adding the Search Tool (Plugin) here:
#     'PLUGINS': {
#         'geosearch': {
#             'js': ['https://unpkg.com'],
#             'css': ['https://unpkg.com'],
#             'auto-include': True,
#         }
#     }

# settings.py

    'PLUGINS': {
        'geocoder': {
           'css': ['https://unpkg.com'],
            'js': ['https://unpkg.com'],
            'auto-include': True,
        }
    }
}



FLUTTERWAVE_SECRET_KEY = os.getenv("FLUTTERWAVE_SECRET_KEY")


REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": (

        # DRF Browser Login
        "rest_framework.authentication.SessionAuthentication",

        # JWT
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),



    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Payroll API",
    "DESCRIPTION": "HR + Payroll System API",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": (
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#     ),

#     "DEFAULT_PERMISSION_CLASSES": (
#         "rest_framework.permissions.IsAuthenticated",
#     ),
# }

 


# LEAFLET_CONFIG = {
#     'DEFAULT_CENTER': (6.5244, 3.3792),
#     'DEFAULT_ZOOM': 12,
#     'TILES': [
#         ('Main Map', 'https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png', 
#          '© OpenStreetMap contributors, Tiles style by Humanitarian OpenStreetMap Team'),
#     ],
#     'ATTRIBUTION_PREFIX': 'Powered by HR Systems',
# }