# Generated by Django 6.0.4 on 2026-04-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_workspaces',
            field=models.ManyToManyField(related_name='employees', to='attendance.workspace'),
        ),
    ]
