# Generated by Django 6.0.4 on 2026-04-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_shift_attendance_clock_out_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='shifts',
            field=models.ManyToManyField(null=True, related_name='workspaces', to='attendance.shift'),
        ),
    ]
