# Generated by Django 6.0.4 on 2026-04-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_workspace_shifts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='workspaces', to='attendance.shift'),
        ),
    ]
