# Generated by Django 6.0.4 on 2026-05-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_workspace_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override default hourly rate for this shift.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='late_penalty_per_minute',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override default late penalty per minute for this shift. ', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='overtime_rate_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override default overtime rate multiplier for this shift.', max_digits=10, null=True),
        ),
    ]
